import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js'

import type { ComputerUseServerRuntime } from './runtime'

import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { createTestConfig } from '../test-fixtures'
import { workspaceKeyFromPath, WorkspaceMemoryStore } from '../workspace-memory/store'
import { registerWorkspaceMemoryTools } from './register-workspace-memory'
import { initializeGlobalRegistry } from './tool-descriptors'

type ToolHandler = (args: Record<string, unknown>) => Promise<CallToolResult>

function createMockServer() {
  const handlers = new Map<string, ToolHandler>()

  return {
    server: {
      tool(...args: unknown[]) {
        const name = args[0] as string
        const handler = args.at(-1) as ToolHandler
        handlers.set(name, handler)
      },
    } as unknown as McpServer,
    async invoke(name: string, args: Record<string, unknown> = {}) {
      const handler = handlers.get(name)
      if (!handler)
        throw new Error(`Missing registered tool: ${name}`)

      return await handler(args)
    },
    hasTool(name: string) {
      return handlers.has(name)
    },
  }
}

describe('registerWorkspaceMemoryTools', () => {
  let tmpRoot: string
  let workspacePath: string
  let runtime: ComputerUseServerRuntime

  beforeEach(async () => {
    initializeGlobalRegistry()
    tmpRoot = await mkdtemp(join(tmpdir(), 'workspace-memory-mcp-'))
    workspacePath = join(tmpRoot, 'repo')
    runtime = {
      config: createTestConfig({ sessionRoot: tmpRoot }),
    } as unknown as ComputerUseServerRuntime
  })

  afterEach(async () => {
    await rm(tmpRoot, { recursive: true, force: true })
  })

  async function createSeedStore() {
    const store = new WorkspaceMemoryStore(
      join(tmpRoot, 'workspace-memory', `${workspaceKeyFromPath(workspacePath)}.jsonl`),
      { workspacePath, sourceRunId: 'seed-run' },
    )
    await store.init()
    return store
  }

  async function jsonlRows(): Promise<string[]> {
    const content = await readFile(join(tmpRoot, 'workspace-memory', `${workspaceKeyFromPath(workspacePath)}.jsonl`), 'utf8')
    return content.trim() ? content.trim().split('\n') : []
  }

  it('registers request-only workspace memory MCP review tools without mutation or coding model-loop names', () => {
    const { server, hasTool } = createMockServer()

    registerWorkspaceMemoryTools(server, runtime)

    expect(hasTool('workspace_memory_list')).toBe(true)
    expect(hasTool('workspace_memory_read')).toBe(true)
    expect(hasTool('workspace_memory_request_review')).toBe(true)
    expect(hasTool('workspace_memory_list_review_requests')).toBe(true)
    expect(hasTool('workspace_memory_read_review_request')).toBe(true)
    expect(hasTool('workspace_memory_review')).toBe(false)
    expect(hasTool('workspace_memory_approve_review_request')).toBe(false)
    expect(hasTool('workspace_memory_reject_review_request')).toBe(false)
    expect(hasTool('coding_review_workspace_memory')).toBe(false)
    expect(hasTool('coding_update_workspace_memory')).toBe(false)
    expect(hasTool('coding_activate_workspace_memory')).toBe(false)
  })

  it('lists proposed entries by default and supports explicit status filters', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'constraint',
      statement: 'Proposed memory needs external review.',
      evidence: 'Generated by the coding runner proposal tool.',
      confidence: 'medium',
    })
    const active = await seedStore.propose({
      kind: 'fact',
      statement: 'Active memory is prompt eligible.',
      evidence: 'Maintainer reviewed this fact.',
      confidence: 'high',
    })
    await seedStore.review({
      id: active.id,
      decision: 'activate',
      reviewer: 'maintainer',
      rationale: 'Verified active memory.',
    })

    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const defaultResult = await invoke('workspace_memory_list', { workspacePath })
    expect(defaultResult.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'governed_workspace_memory_not_instructions',
      statusFilter: 'proposed',
    })
    const defaultEntries = (defaultResult.structuredContent as any).entries
    expect(defaultEntries).toHaveLength(1)
    expect(defaultEntries[0].id).toBe(proposed.id)

    const activeResult = await invoke('workspace_memory_list', { workspacePath, status: 'active', query: 'prompt eligible' })
    const activeEntries = (activeResult.structuredContent as any).entries
    expect(activeEntries).toHaveLength(1)
    expect(activeEntries[0]).toMatchObject({
      id: active.id,
      status: 'active',
      humanVerified: true,
    })
  })

  it('reads a workspace memory entry as governed review data', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'pitfall',
      statement: 'Do not auto-promote archive findings.',
      evidence: 'Archive recall remains historical evidence, not workspace truth.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_read', { workspacePath, id: proposed.id })

    expect(result.isError).toBeUndefined()
    expect(result.content[0]).toMatchObject({
      type: 'text',
      text: expect.stringContaining('not executable instructions'),
    })
    expect(result.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'governed_workspace_memory_not_instructions',
      entry: {
        id: proposed.id,
        status: 'proposed',
        evidence: 'Archive recall remains historical evidence, not workspace truth.',
      },
    })
  })

  it('returns read errors for missing ids without mutating memory', async () => {
    const seedStore = await createSeedStore()
    await seedStore.propose({
      kind: 'fact',
      statement: 'Read errors should not mutate memory.',
      evidence: 'Missing ids are reported as structured errors.',
    })
    const rowsBefore = await jsonlRows()
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_read', {
      workspacePath,
      id: 'missing',
    })

    expect(result.isError).toBe(true)
    expect(result.structuredContent).toMatchObject({
      status: 'error',
      error: 'Workspace memory entry not found: missing',
    })
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
  })

  it('creates pending review requests without changing workspace memory status', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'constraint',
      statement: 'Review requests are not automatic activation.',
      evidence: 'MCP request review is request-only.',
      confidence: 'medium',
    })
    const rowsBefore = await jsonlRows()
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Looks durable, but still needs host-gated apply.',
    })

    expect(result.isError).toBeUndefined()
    expect(result.structuredContent).toMatchObject({
      status: 'approval_required',
      trust: 'workspace_memory_review_request_not_instructions',
      pendingReviewId: expect.any(String),
      request: {
        memoryId: proposed.id,
        decision: 'activate',
        requester: 'maintainer',
        rationale: 'Looks durable, but still needs host-gated apply.',
        status: 'pending',
        targetStatus: 'proposed',
        targetStatement: proposed.statement,
      },
    })
    expect(seedStore.read(proposed.id)?.status).toBe('proposed')
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
  })

  it('lists and reads pending review requests as governance data', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'fact',
      statement: 'Pending requests are separate governance data.',
      evidence: 'Review request store is append-only.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Review this proposed fact.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId

    const listResult = await invoke('workspace_memory_list_review_requests', {
      workspacePath,
      query: 'separate governance',
    })
    expect(listResult.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'workspace_memory_review_request_not_instructions',
      requests: [
        {
          id: pendingReviewId,
          memoryId: proposed.id,
          status: 'pending',
        },
      ],
    })

    const readResult = await invoke('workspace_memory_read_review_request', {
      workspacePath,
      id: pendingReviewId,
    })
    expect(readResult.content[0]).toMatchObject({
      type: 'text',
      text: expect.stringContaining('not executable instructions'),
    })
    expect(readResult.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'workspace_memory_review_request_not_instructions',
      request: {
        id: pendingReviewId,
        memoryId: proposed.id,
        decision: 'activate',
      },
    })
  })

  it('returns review request errors without mutating memory or creating requests', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'fact',
      statement: 'Review request errors should not mutate memory.',
      evidence: 'Invalid requests fail before appending request rows.',
    })
    const rowsBefore = await jsonlRows()
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: ' ',
      rationale: 'Valid rationale.',
    })

    expect(result.isError).toBe(true)
    expect(result.structuredContent).toMatchObject({
      status: 'error',
      trust: 'workspace_memory_review_request_not_instructions',
      error: expect.stringContaining('requester is required'),
    })
    expect(seedStore.read(proposed.id)?.status).toBe('proposed')
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
  })
})
