import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js'

import type { ComputerUseServerRuntime } from './runtime'

import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { createTestConfig } from '../test-fixtures'
import { workspaceKeyFromPath, WorkspaceMemoryStore } from '../workspace-memory/store'
import { registerWorkspaceMemoryTools } from './register-workspace-memory'
import { initializeGlobalRegistry } from './tool-descriptors'

type ToolHandler = (args: Record<string, unknown>) => Promise<CallToolResult>

function createMockServer() {
  const handlers = new Map<string, ToolHandler>()

  return {
    server: {
      tool(...args: unknown[]) {
        const name = args[0] as string
        const handler = args.at(-1) as ToolHandler
        handlers.set(name, handler)
      },
    } as unknown as McpServer,
    async invoke(name: string, args: Record<string, unknown> = {}) {
      const handler = handlers.get(name)
      if (!handler)
        throw new Error(`Missing registered tool: ${name}`)

      return await handler(args)
    },
    hasTool(name: string) {
      return handlers.has(name)
    },
  }
}

describe('registerWorkspaceMemoryTools', () => {
  let tmpRoot: string
  let workspacePath: string
  let runtime: ComputerUseServerRuntime

  beforeEach(async () => {
    initializeGlobalRegistry()
    tmpRoot = await mkdtemp(join(tmpdir(), 'workspace-memory-mcp-'))
    workspacePath = join(tmpRoot, 'repo')
    runtime = {
      config: createTestConfig({ sessionRoot: tmpRoot }),
    } as unknown as ComputerUseServerRuntime
  })

  afterEach(async () => {
    await rm(tmpRoot, { recursive: true, force: true })
  })

  async function createSeedStore() {
    const store = new WorkspaceMemoryStore(
      join(tmpRoot, 'workspace-memory', `${workspaceKeyFromPath(workspacePath)}.jsonl`),
      { workspacePath, sourceRunId: 'seed-run' },
    )
    await store.init()
    return store
  }

  async function jsonlRows(): Promise<string[]> {
    const content = await readFile(join(tmpRoot, 'workspace-memory', `${workspaceKeyFromPath(workspacePath)}.jsonl`), 'utf8')
    return content.trim() ? content.trim().split('\n') : []
  }

  async function reviewRequestRows(): Promise<string[]> {
    const content = await readFile(join(tmpRoot, 'workspace-memory-review-requests', `${workspaceKeyFromPath(workspacePath)}.jsonl`), 'utf8')
    return content.trim() ? content.trim().split('\n') : []
  }

  it('registers authorized workspace memory review apply tools without generic or coding model-loop names', () => {
    const { server, hasTool } = createMockServer()

    registerWorkspaceMemoryTools(server, runtime)

    expect(hasTool('workspace_memory_list')).toBe(true)
    expect(hasTool('workspace_memory_read')).toBe(true)
    expect(hasTool('workspace_memory_request_review')).toBe(true)
    expect(hasTool('workspace_memory_list_review_requests')).toBe(true)
    expect(hasTool('workspace_memory_read_review_request')).toBe(true)
    expect(hasTool('workspace_memory_apply_review_request')).toBe(true)
    expect(hasTool('workspace_memory_reject_review_request')).toBe(true)
    expect(hasTool('workspace_memory_review')).toBe(false)
    expect(hasTool('workspace_memory_approve_review_request')).toBe(false)
    expect(hasTool('coding_review_workspace_memory')).toBe(false)
    expect(hasTool('coding_update_workspace_memory')).toBe(false)
    expect(hasTool('coding_activate_workspace_memory')).toBe(false)
  })

  it('lists proposed entries by default and supports explicit status filters', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'constraint',
      statement: 'Proposed memory needs external review.',
      evidence: 'Generated by the coding runner proposal tool.',
      confidence: 'medium',
    })
    const active = await seedStore.propose({
      kind: 'fact',
      statement: 'Active memory is prompt eligible.',
      evidence: 'Maintainer reviewed this fact.',
      confidence: 'high',
    })
    await seedStore.review({
      id: active.id,
      decision: 'activate',
      reviewer: 'maintainer',
      rationale: 'Verified active memory.',
    })

    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const defaultResult = await invoke('workspace_memory_list', { workspacePath })
    expect(defaultResult.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'governed_workspace_memory_not_instructions',
      statusFilter: 'proposed',
    })
    const defaultEntries = (defaultResult.structuredContent as any).entries
    expect(defaultEntries).toHaveLength(1)
    expect(defaultEntries[0].id).toBe(proposed.id)

    const activeResult = await invoke('workspace_memory_list', { workspacePath, status: 'active', query: 'prompt eligible' })
    const activeEntries = (activeResult.structuredContent as any).entries
    expect(activeEntries).toHaveLength(1)
    expect(activeEntries[0]).toMatchObject({
      id: active.id,
      status: 'active',
      humanVerified: true,
    })
  })

  it('reads a workspace memory entry as governed review data', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'pitfall',
      statement: 'Do not auto-promote archive findings.',
      evidence: 'Archive recall remains historical evidence, not workspace truth.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_read', { workspacePath, id: proposed.id })

    expect(result.isError).toBeUndefined()
    expect(result.content[0]).toMatchObject({
      type: 'text',
      text: expect.stringContaining('not executable instructions'),
    })
    expect(result.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'governed_workspace_memory_not_instructions',
      entry: {
        id: proposed.id,
        status: 'proposed',
        evidence: 'Archive recall remains historical evidence, not workspace truth.',
      },
    })
  })

  it('returns read errors for missing ids without mutating memory', async () => {
    const seedStore = await createSeedStore()
    await seedStore.propose({
      kind: 'fact',
      statement: 'Read errors should not mutate memory.',
      evidence: 'Missing ids are reported as structured errors.',
    })
    const rowsBefore = await jsonlRows()
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_read', {
      workspacePath,
      id: 'missing',
    })

    expect(result.isError).toBe(true)
    expect(result.structuredContent).toMatchObject({
      status: 'error',
      error: 'Workspace memory entry not found: missing',
    })
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
  })

  it('creates pending review requests without changing workspace memory status', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'constraint',
      statement: 'Review requests are not automatic activation.',
      evidence: 'MCP request review is request-only.',
      confidence: 'medium',
    })
    const rowsBefore = await jsonlRows()
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Looks durable, but still needs host-gated apply.',
    })

    expect(result.isError).toBeUndefined()
    expect(result.structuredContent).toMatchObject({
      status: 'approval_required',
      trust: 'workspace_memory_review_request_not_instructions',
      pendingReviewId: expect.any(String),
      request: {
        memoryId: proposed.id,
        decision: 'activate',
        requester: 'maintainer',
        rationale: 'Looks durable, but still needs host-gated apply.',
        status: 'pending',
        targetStatus: 'proposed',
        targetStatement: proposed.statement,
      },
    })
    expect(seedStore.read(proposed.id)?.status).toBe('proposed')
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
  })

  it('lists and reads pending review requests as governance data', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'fact',
      statement: 'Pending requests are separate governance data.',
      evidence: 'Review request store is append-only.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Review this proposed fact.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId

    const listResult = await invoke('workspace_memory_list_review_requests', {
      workspacePath,
      query: 'separate governance',
    })
    expect(listResult.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'workspace_memory_review_request_not_instructions',
      requests: [
        {
          id: pendingReviewId,
          memoryId: proposed.id,
          status: 'pending',
        },
      ],
    })

    const readResult = await invoke('workspace_memory_read_review_request', {
      workspacePath,
      id: pendingReviewId,
    })
    expect(readResult.content[0]).toMatchObject({
      type: 'text',
      text: expect.stringContaining('not executable instructions'),
    })
    expect(readResult.structuredContent).toMatchObject({
      status: 'ok',
      trust: 'workspace_memory_review_request_not_instructions',
      request: {
        id: pendingReviewId,
        memoryId: proposed.id,
        decision: 'activate',
      },
    })
  })

  it('returns review request errors without mutating memory or creating requests', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'fact',
      statement: 'Review request errors should not mutate memory.',
      evidence: 'Invalid requests fail before appending request rows.',
    })
    const rowsBefore = await jsonlRows()
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)

    const result = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: ' ',
      rationale: 'Valid rationale.',
    })

    expect(result.isError).toBe(true)
    expect(result.structuredContent).toMatchObject({
      status: 'error',
      trust: 'workspace_memory_review_request_not_instructions',
      error: expect.stringContaining('requester is required'),
    })
    expect(seedStore.read(proposed.id)?.status).toBe('proposed')
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
  })

  it('rejects review apply when apply token is not configured', async () => {
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'constraint',
      statement: 'Apply is disabled without token.',
      evidence: 'Host must configure a review apply token.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)
    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Request activation.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId
    const rowsBefore = await jsonlRows()

    const result = await invoke('workspace_memory_apply_review_request', {
      workspacePath,
      id: pendingReviewId,
      approver: 'host',
      rationale: 'Authorized by host.',
      approvalToken: 'secret-token',
    })

    expect(result.isError).toBe(true)
    expect(result.content[0]).toMatchObject({
      type: 'text',
      text: expect.not.stringContaining('secret-token'),
    })
    expect(result.structuredContent).toMatchObject({
      status: 'error',
      trust: 'workspace_memory_review_request_not_instructions',
      code: 'WORKSPACE_MEMORY_REVIEW_APPLY_DISABLED',
    })
    expect(seedStore.read(proposed.id)?.status).toBe('proposed')
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
  })

  it('rejects review apply with a wrong token without echoing it', async () => {
    runtime.config.workspaceMemoryReviewApplyToken = 'correct-token'
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'fact',
      statement: 'Wrong tokens cannot apply review requests.',
      evidence: 'The tool must compare approval tokens.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)
    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Request activation.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId

    const result = await invoke('workspace_memory_apply_review_request', {
      workspacePath,
      id: pendingReviewId,
      approver: 'host',
      rationale: 'Authorized by host.',
      approvalToken: 'wrong-token',
    })

    expect(result.isError).toBe(true)
    expect(JSON.stringify(result)).not.toContain('wrong-token')
    expect(result.structuredContent).toMatchObject({
      status: 'error',
      code: 'WORKSPACE_MEMORY_REVIEW_APPLY_DENIED',
    })
    expect(seedStore.read(proposed.id)?.status).toBe('proposed')
  })

  it('applies review requests with a correct token through WorkspaceMemoryStore.review', async () => {
    runtime.config.workspaceMemoryReviewApplyToken = 'correct-token'
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'constraint',
      statement: 'Authorized apply can activate governed memory.',
      evidence: 'The host supplied the apply token.',
      confidence: 'high',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)
    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Request activation.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId

    const result = await invoke('workspace_memory_apply_review_request', {
      workspacePath,
      id: pendingReviewId,
      approver: 'host',
      rationale: 'Verified by external host.',
      approvalToken: 'correct-token',
    })

    expect(result.isError).toBeUndefined()
    expect(JSON.stringify(result)).not.toContain('correct-token')
    expect(result.structuredContent).toMatchObject({
      status: 'applied',
      trust: 'workspace_memory_review_request_not_instructions',
      request: {
        id: pendingReviewId,
        status: 'applied',
        resolvedBy: 'host',
        resolutionRationale: 'Verified by external host.',
        appliedMemoryStatus: 'active',
      },
      entry: {
        id: proposed.id,
        status: 'active',
        humanVerified: true,
      },
    })

    const reloaded = await createSeedStore()
    expect(reloaded.read(proposed.id)).toMatchObject({
      status: 'active',
      humanVerified: true,
      review: {
        decision: 'activate',
        reviewer: 'host',
        rationale: 'Verified by external host.',
      },
    })
  })

  it('returns WORKSPACE_MEMORY_REVIEW_TARGET_STALE when applying a request whose target memory changed', async () => {
    runtime.config.workspaceMemoryReviewApplyToken = 'correct-token'
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'constraint',
      statement: 'Stale review requests must not activate changed memory.',
      evidence: 'Review request snapshots must match the target entry.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)
    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Request activation before target changes.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId
    await seedStore.review({
      id: proposed.id,
      decision: 'reject',
      reviewer: 'maintainer',
      rationale: 'Target changed before authorized apply.',
    })
    const memoryRowsBeforeApply = await jsonlRows()

    const result = await invoke('workspace_memory_apply_review_request', {
      workspacePath,
      id: pendingReviewId,
      approver: 'host',
      rationale: 'Attempt stale apply.',
      approvalToken: 'correct-token',
    })

    expect(result.isError).toBe(true)
    expect(result.structuredContent).toMatchObject({
      status: 'error',
      trust: 'workspace_memory_review_request_not_instructions',
      code: 'WORKSPACE_MEMORY_REVIEW_TARGET_STALE',
    })
    expect(seedStore.read(proposed.id)?.status).toBe('rejected')
    expect(await jsonlRows()).toHaveLength(memoryRowsBeforeApply.length)

    const readResult = await invoke('workspace_memory_read_review_request', {
      workspacePath,
      id: pendingReviewId,
    })
    expect(readResult.structuredContent).toMatchObject({
      status: 'ok',
      request: {
        id: pendingReviewId,
        status: 'stale',
        resolvedBy: 'host',
        resolutionRationale: 'Attempt stale apply.',
        errorCode: 'target_status_changed',
      },
    })
  })

  it('rejects review requests with a correct token without changing memory status', async () => {
    runtime.config.workspaceMemoryReviewApplyToken = 'correct-token'
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'pitfall',
      statement: 'Rejecting a request should not reject memory.',
      evidence: 'Request rejection is separate from applying a reject decision.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)
    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'reject',
      requester: 'maintainer',
      rationale: 'Request memory rejection.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId
    const rowsBefore = await jsonlRows()

    const result = await invoke('workspace_memory_reject_review_request', {
      workspacePath,
      id: pendingReviewId,
      approver: 'host',
      rationale: 'Do not apply this request.',
      approvalToken: 'correct-token',
    })

    expect(result.isError).toBeUndefined()
    expect(result.structuredContent).toMatchObject({
      status: 'rejected',
      request: {
        id: pendingReviewId,
        status: 'rejected',
        resolvedBy: 'host',
        resolutionRationale: 'Do not apply this request.',
      },
    })
    expect(seedStore.read(proposed.id)?.status).toBe('proposed')
    expect(await jsonlRows()).toHaveLength(rowsBefore.length)
    expect(await reviewRequestRows()).toHaveLength(2)
  })

  it('lists resolved review requests only when explicitly requested', async () => {
    runtime.config.workspaceMemoryReviewApplyToken = 'correct-token'
    const seedStore = await createSeedStore()
    const proposed = await seedStore.propose({
      kind: 'fact',
      statement: 'Resolved requests are still auditable.',
      evidence: 'List supports explicit status filters.',
    })
    const { server, invoke } = createMockServer()
    registerWorkspaceMemoryTools(server, runtime)
    const requestResult = await invoke('workspace_memory_request_review', {
      workspacePath,
      id: proposed.id,
      decision: 'activate',
      requester: 'maintainer',
      rationale: 'Request activation.',
    })
    const pendingReviewId = (requestResult.structuredContent as any).pendingReviewId
    await invoke('workspace_memory_apply_review_request', {
      workspacePath,
      id: pendingReviewId,
      approver: 'host',
      rationale: 'Verified.',
      approvalToken: 'correct-token',
    })

    const defaultList = await invoke('workspace_memory_list_review_requests', { workspacePath })
    expect((defaultList.structuredContent as any).requests).toEqual([])

    const appliedList = await invoke('workspace_memory_list_review_requests', {
      workspacePath,
      status: 'applied',
    })
    expect(appliedList.structuredContent).toMatchObject({
      status: 'ok',
      statusFilter: 'applied',
      requests: [
        {
          id: pendingReviewId,
          status: 'applied',
        },
      ],
    })

    const readResult = await invoke('workspace_memory_read_review_request', {
      workspacePath,
      id: pendingReviewId,
    })
    expect(readResult.structuredContent).toMatchObject({
      status: 'ok',
      request: {
        id: pendingReviewId,
        status: 'applied',
      },
    })
  })
})
